# Generated by Django 4.2.4 on 2023-08-29 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileDataHandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=40)),
                ("file_type", models.CharField(max_length=10)),
                ("file_location", models.CharField(max_length=100)),
                ("file_size", models.CharField(max_length=20)),
                ("date_time", models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="FileName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameZone", models.CharField(max_length=5)),
            ],
        ),
    ]
